name: Train MNIST Model

on: [push]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run training
      run: |
        python assign6.py | tee training.log
    
    - name: Update README with results
      run: |
        # Extract maximum accuracy from training log
        MAX_ACC=$(grep "Maximum Accuracy achieved:" training.log | tail -n 1)
        
        # Update README.md
        sed -i "/<!-- LATEST_RESULT -->/,/<!-- END_LATEST_RESULT -->/c\<!-- LATEST_RESULT -->\n${MAX_ACC}\n<!-- END_LATEST_RESULT -->" README.md
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update training results" || exit 0
        git push 